# Generated by Django 5.0.4 on 2024-05-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_number',
        ),
    ]
